### ISSUE TITLE
Is there any intent to meet the CommonMark spec

### ISSUE THREAD

**Issue by sabracrolleton** [3b/3bmd#27] opened 2016-02-21 18:53 UTC
Is there any intent to meet the new spec at http://spec.commonmark.org/?

**Comment by 3b** [comment] 2016-06-29 21:10
I would like to at some point, but my coding time is fairly limited currently, so not sure when I will be able to work on it.

Closing as a duplicate of #16

**Closed by 3b** 2016-06-29 21:10 UTC
